"""3.2: add customers table with name and phone normalization

Revision ID: 2babb87a0e74
Revises: c0f1b5098dd9
Create Date: 2026-08-17 17:43:01.944566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2babb87a0e74'
down_revision: Union[str, Sequence[str], None] = 'c0f1b5098dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.String(length=255), nullable=False),
    sa.Column('name_display', sa.String(length=255), nullable=False),
    sa.Column('name_key', sa.String(length=255), nullable=False),
    sa.Column('phone_raw', sa.String(length=20), nullable=True),
    sa.Column('phone_key', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name_key'), ['name_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_key'), ['phone_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone_key'))
        batch_op.drop_index(batch_op.f('ix_customers_name_key'))
        batch_op.drop_index(batch_op.f('ix_customers_created_at'))

    op.drop_table('customers')
    # ### end Alembic commands ###
