"""3.3: add customer, delivery address, and tax rate snapshots to orders

Revision ID: 3f7497e36472
Revises: 2babb87a0e74
Create Date: 2026-08-17 18:10:12.807777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7497e36472'
down_revision: Union[str, Sequence[str], None] = '2babb87a0e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_customer_id_customers', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###

    # Backfill tax_rate = 0 for all existing orders
    # Tax has been disabled throughout; orders.tax column exists but tax_rate snapshot was missing (Rule 7)
    op.execute("UPDATE orders SET tax_rate = 0 WHERE tax_rate IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_customer_id_customers', type_='foreignkey')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
