"""3.4: add delivery_charge to settings and orders

Revision ID: d04a3262b373
Revises: 3f7497e36472
Create Date: 2026-08-17 19:46:18.591475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04a3262b373'
down_revision: Union[str, Sequence[str], None] = '3f7497e36472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds delivery_charge to both settings and orders (Rule 7 snapshot).

    settings.delivery_charge:
    - NOT NULL with server_default='0' (paisa, default 0)
    - Protects existing row during ALTER TABLE
    - Per docs/SETUP.md: NEW NOT NULL columns on existing tables need server_default

    orders.delivery_charge:
    - Nullable (null for non-delivery orders)
    - Stores the charge applied at order time (snapshot per Rule 7)
    - Backfilled to 0 for all existing orders
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_charge', sa.Integer(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_charge', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

    # Backfill existing orders to delivery_charge = 0
    op.execute('UPDATE orders SET delivery_charge = 0')


def downgrade() -> None:
    """Downgrade schema.

    Reversible: dropping columns does not lose data permanently in SQLite (data
    remains in the database file's unused space). However, undoing a migration
    that added delivery_charge would require re-creating the columns if they
    were used. Normally not recommended in production; restore from
    pos.db.backup.3.4 if a rollback is needed.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('delivery_charge')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_charge')

    # ### end Alembic commands ###
