"""add settings table

Revision ID: e70842f37507
Revises: b2c3d4e5f6a1
Create Date: 2026-08-16 14:08:36.676340

Task 1.1 — Settings table and SettingsContext (Rule 1).

This migration creates the single-row settings table with:
- CHECK constraint (id = 1) preventing any row other than id=1
- DELETE trigger preventing accidental deletion
- Data migration (INSERT) creating the default row

CRITICAL: The DELETE trigger may vanish silently when SQLite rebuilds the table
(e.g., when adding a new column in Stage 3). After any ALTER TABLE on this table,
verify the trigger exists:
    SELECT name, sql FROM sqlite_master WHERE type='trigger' AND name='prevent_settings_delete';
If missing, see docs/SETUP.md for trigger recreation instructions.
"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70842f37507'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create settings table with constraint, trigger, and default row."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=150), nullable=False),
    sa.Column('restaurant_address', sa.String(length=300), nullable=False),
    sa.Column('restaurant_phone', sa.String(length=20), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('day_starts_at', sa.String(length=5), nullable=False),
    sa.Column('receipt_footer_text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='check_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Create DELETE trigger to prevent accidental row deletion
    op.execute(
        """
        CREATE TRIGGER prevent_settings_delete
        BEFORE DELETE ON settings
        BEGIN
          SELECT RAISE(ABORT, 'Cannot delete settings row');
        END
        """
    )

    # Insert default settings row (data migration)
    now = datetime.utcnow().isoformat()
    op.execute(
        f"""
        INSERT INTO settings
        (id, restaurant_name, restaurant_address, restaurant_phone, currency_symbol,
         tax_rate, tax_enabled, day_starts_at, receipt_footer_text, created_at, updated_at)
        VALUES
        (1, 'My Restaurant', '', '', 'Rs. ', 0, 0, '06:00', 'Please visit us again.', '{now}', '{now}')
        """
    )


def downgrade() -> None:
    """Downgrade schema: drop trigger and table."""
    # Drop trigger before dropping table
    op.execute("DROP TRIGGER IF EXISTS prevent_settings_delete")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
